name: media_picker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  open_file: ^3.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
